import test from 'node:test';import assert from 'node:assert/strict';import worker,{validateEnquiry} from '../worker/enquiry.js';
const valid={name:'Alex Smith',email:'alex@example.com',interestType:'Buyer',area:'NR1',message:'Please tell me when FreshLocal launches.',consent:true,company:''};
function req(body=valid,o={}){return new Request(o.url||'https://freshlocal.org.uk/api/enquiry',{method:o.method||'POST',headers:{Origin:o.origin||'https://freshlocal.org.uk','Content-Type':o.contentType||'application/json'},body:(o.method||'POST')==='POST'?JSON.stringify(body):undefined})}
test('validates and normalises',()=>{const r=validateEnquiry({...valid,email:'  ALEX@EXAMPLE.COM  '});assert.equal(r.ok,true);assert.equal(r.data.email,'alex@example.com')});
test('rejects invalid fields',()=>{const r=validateEnquiry({name:'',email:'bad',interestType:'Robot',area:'x'.repeat(101),message:'x'.repeat(2001),consent:false});assert.equal(r.ok,false);assert.deepEqual(Object.keys(r.errors).sort(),['area','consent','email','interestType','message','name'])});
test('sends only to fixed destination',async()=>{let sent;const response=await worker.fetch(req(),{ENQUIRY_EMAIL:{send:async m=>{sent=m}}});assert.equal(response.status,200);assert.equal(sent.to,'freshlocal@protonmail.com');assert.equal(sent.from,'enquiries@freshlocal.org.uk');assert.equal(sent.replyTo,valid.email)});
test('honeypot does not send',async()=>{let calls=0;const response=await worker.fetch(req({...valid,company:'spam.example'}),{ENQUIRY_EMAIL:{send:async()=>calls++}});assert.equal(response.status,200);assert.equal(calls,0)});
test('restricts origins',async()=>{const response=await worker.fetch(req(valid,{origin:'https://example.com'}),{});assert.equal(response.status,403);assert.equal(response.headers.get('Access-Control-Allow-Origin'),null)});
test('allows www origin',async()=>{const response=await worker.fetch(req(valid,{origin:'https://www.freshlocal.org.uk'}),{ENQUIRY_EMAIL:{send:async()=>{}}});assert.equal(response.status,200);assert.equal(response.headers.get('Access-Control-Allow-Origin'),'https://www.freshlocal.org.uk')});
test('allows localhost only in development',async()=>{const local=req(valid,{origin:'http://127.0.0.1:8787'});assert.equal((await worker.fetch(local.clone(),{ENQUIRY_EMAIL:{send:async()=>{}},ENVIRONMENT:'development'})).status,200);assert.equal((await worker.fetch(local,{ENQUIRY_EMAIL:{send:async()=>{}}})).status,403)});
test('rejects method path and content type',async()=>{assert.equal((await worker.fetch(req(valid,{method:'GET'}),{})).status,405);assert.equal((await worker.fetch(req(valid,{url:'https://freshlocal.org.uk/api/other'}),{})).status,404);assert.equal((await worker.fetch(req(valid,{contentType:'text/plain'}),{})).status,415)});
test('returns safe delivery failure',async()=>{const response=await worker.fetch(req(),{ENQUIRY_EMAIL:{send:async()=>{throw Object.assign(new Error('secret'),{code:'E_DELIVERY_FAILED'})}}});assert.equal(response.status,502);assert.equal((await response.text()).includes('secret'),false)});
